apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        adithya180498/-node-http-watch-pipeline-activity: true
        adithya180498/angular: true
        adithya180498/angular-io-quickstart: true
        adithya180498/asp: true
        adithya180498/bs: true
        adithya180498/dlang-http: true
        adithya180498/golang-http: true
        adithya180498/jx3-k3s-vault1: true
        adithya180498/node-http: true
        adithya180498/node-postgresql: true
        adithya180498/rust-http: true
        adithya180498/vertx-rest-prometheus: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        adithya180498/-node-http-watch-pipeline-activity: merge
        adithya180498/angular: merge
        adithya180498/angular-io-quickstart: merge
        adithya180498/asp: merge
        adithya180498/bs: merge
        adithya180498/dlang-http: merge
        adithya180498/golang-http: merge
        adithya180498/jx3-k3s-vault1: merge
        adithya180498/node-http: merge
        adithya180498/node-postgresql: merge
        adithya180498/rust-http: merge
        adithya180498/vertx-rest-prometheus: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - adithya180498/jx3-k3s-vault1
        - adithya180498/angular-io-quickstart
        - adithya180498/angular
        - adithya180498/asp
        - adithya180498/bs
        - adithya180498/dlang-http
        - adithya180498/golang-http
        - adithya180498/-node-http-watch-pipeline-activity
        - adithya180498/node-http
        - adithya180498/node-postgresql
        - adithya180498/rust-http
        - adithya180498/vertx-rest-prometheus
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - adithya180498/jx3-k3s-vault1
        - adithya180498/angular-io-quickstart
        - adithya180498/angular
        - adithya180498/asp
        - adithya180498/bs
        - adithya180498/dlang-http
        - adithya180498/golang-http
        - adithya180498/-node-http-watch-pipeline-activity
        - adithya180498/node-http
        - adithya180498/node-postgresql
        - adithya180498/rust-http
        - adithya180498/vertx-rest-prometheus
      target_url: http://lighthouse.jx.172.31.42.234.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
